gui:
  showFileTree: true
  showIcons: true
  showBottomLine: false
  theme:
    activeBorderColor:
      - "#b7bdf8"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#b7bdf8"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
  authorColors:
    "*": "#b7bdf8"
git:
  commit:
    signOff: true
  log:
    showGraph: always
  overrideGpg: true
notARepository: "skip"
keybinding:
  commits:
    openLogMenu: "["
customCommands:
  - key: "<c-g>"
    command: "code ."
    context: "global"
os:
  editPreset: 'code'
